if(EXISTS "/mnt/c/Users/FIRAT/Desktop/00/00/build_linux/src/tests/pomodoro/pomodoro_tests[1]_tests.cmake")
  include("/mnt/c/Users/FIRAT/Desktop/00/00/build_linux/src/tests/pomodoro/pomodoro_tests[1]_tests.cmake")
else()
  add_test(pomodoro_tests_NOT_BUILT pomodoro_tests_NOT_BUILT)
endif()
