add_test( pomodoroTest.TestAdd /mnt/c/Users/FIRAT/Desktop/00/00/build_linux/build/Debug/pomodoro_tests [==[--gtest_filter=pomodoroTest.TestAdd]==] --gtest_also_run_disabled_tests)
set_tests_properties( pomodoroTest.TestAdd PROPERTIES WORKING_DIRECTORY /mnt/c/Users/FIRAT/Desktop/00/00/build_linux/src/tests/pomodoro SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( pomodoroTest.TestSubtract /mnt/c/Users/FIRAT/Desktop/00/00/build_linux/build/Debug/pomodoro_tests [==[--gtest_filter=pomodoroTest.TestSubtract]==] --gtest_also_run_disabled_tests)
set_tests_properties( pomodoroTest.TestSubtract PROPERTIES WORKING_DIRECTORY /mnt/c/Users/FIRAT/Desktop/00/00/build_linux/src/tests/pomodoro SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( pomodoroTest.TestMultiply /mnt/c/Users/FIRAT/Desktop/00/00/build_linux/build/Debug/pomodoro_tests [==[--gtest_filter=pomodoroTest.TestMultiply]==] --gtest_also_run_disabled_tests)
set_tests_properties( pomodoroTest.TestMultiply PROPERTIES WORKING_DIRECTORY /mnt/c/Users/FIRAT/Desktop/00/00/build_linux/src/tests/pomodoro SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( pomodoroTest.TestDivide /mnt/c/Users/FIRAT/Desktop/00/00/build_linux/build/Debug/pomodoro_tests [==[--gtest_filter=pomodoroTest.TestDivide]==] --gtest_also_run_disabled_tests)
set_tests_properties( pomodoroTest.TestDivide PROPERTIES WORKING_DIRECTORY /mnt/c/Users/FIRAT/Desktop/00/00/build_linux/src/tests/pomodoro SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( pomodoroTest.TestDivideByZero /mnt/c/Users/FIRAT/Desktop/00/00/build_linux/build/Debug/pomodoro_tests [==[--gtest_filter=pomodoroTest.TestDivideByZero]==] --gtest_also_run_disabled_tests)
set_tests_properties( pomodoroTest.TestDivideByZero PROPERTIES WORKING_DIRECTORY /mnt/c/Users/FIRAT/Desktop/00/00/build_linux/src/tests/pomodoro SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( pomodoro_tests_TESTS pomodoroTest.TestAdd pomodoroTest.TestSubtract pomodoroTest.TestMultiply pomodoroTest.TestDivide pomodoroTest.TestDivideByZero)
